### PR TITLE
translation into Indonesian documentation.rst

### PR DESCRIPTION
**Pull request by mohdhaekal**
I've translated the documentation.rst file into Indonesian
please be seen and in merge

### CODE REVIEW

**Comment by kennethreitz** [comment]
so, what needs to happen here is you need to keep your fork alive on github and set it up on readthedocs.org.

**Comment by kennethreitz** [comment]
then, you send a pull request linking to your documentation in the sidebar

**Comment by mohdhaekal** [comment]
so how do I enter the file here

**Comment by mohdhaekal** [comment]
I want to put it on readthedocs.org
so how can i put it

**Pull request closed without merging**
