### PR TITLE
Update doc link from 2 to 3

### PR DESCRIPTION
**Pull request by nikolas**

### CODE REVIEW

**Comment by sigmavirus24** [comment]
I'll let @kennethreitz handle this one

**Comment by kennethreitz** [comment]
so many feels

**Comment by kennethreitz** [comment]
this should probally happen all over the guide, honestly

**Comment by kennethreitz** [comment]
i mean, if we want to take ourselves seriously

**Comment by kennethreitz** [comment]
I say this because Python 3 adoption has been (slowly) increasing, for the first time in a while, and it appears as though this is because of Django using Python 3 by default in its documentation.

**Comment by nikolas** [comment]
Yeah, I noticed after opening this PR that a lot of the python guide is python2-specific, e.g. http://docs.python-guide.org/en/latest/dev/virtualenvs/, so this PR isn't really valid.

**Comment by sigmavirus24** [comment]
> I say this because Python 3 adoption has been (slowly) increasing, for the first time in a while, and it appears as though this is because of Django using Python 3 by default in its documentation.

Yeah, I also suspect it's because when you go to python.org to download Python it's the first one listed.

**Pull request closed without merging**
