### PR TITLE
add example to mutable/immutable types

### PR DESCRIPTION
**Pull request by danshorstein**
added the map example, with explanation

### CODE REVIEW

**Comment by userlerueda** [comment]
@danshorstein is this related to an open issue?

**Comment by danshorstein** [comment]
No, I just thought it might be useful to put in, I thought of it while
reading through the guide.

**Comment by userlerueda** [comment]
@kennethreitz can confirm this but shouldn't the merge be into master?

**Comment by danshorstein** [comment]
Oh probably, that makes sense, I'm still learning how to properly use
github =P

**Comment by kennethreitz** [comment]
i'll merge this into master

**Comment by kennethreitz** [comment]
merged!

**Comment by danshorstein** [comment]
awesome thanks!

**Pull request closed without merging**
