### PR TITLE
Update `gotchas.rst` to make the sentence simpler

### PR DESCRIPTION
**Pull request by avinassh**
This is follow up PR for #556, since original submitter did not respond I thought of sending this. Feel free to close this.

:beers:

### CODE REVIEW

**Comment by sigmavirus24** [comment]
This didn't actually do what I suggested. I suggested leaving the comma and removing ` though`.

**Comment by avinassh** [comment]
Oops. Let me correct it.

**Comment by avinassh** [comment]
Hi @sigmavirus24, I have updated the PR.

**Comment by sigmavirus24** [comment]
Thanks @avinassh

**Comment by avinassh** [comment]
:beers:

**Pull request merged**
