### PR TITLE
Fixing the urls pointing to the contribute page

### PR DESCRIPTION
**Pull request by vpzee**

### CODE REVIEW

**Comment by sigmavirus24** [comment]
Please use ``http://docs.python-guide.org/en/latest/notes/contribute.html`` instead of the `readthedocs.org` URL.

**Comment by vpzee** [comment]
Thanks for the correct URL.

**Comment by sigmavirus24** [comment]
It's not worth my being a stickler about *this* time but in the future @vpzee please do not make various other formatting changes in a pull request that has nothing to do with them.

Thanks for fixing this link! :cake:

**Comment by vpzee** [comment]
This was my first contribution ever. I can use every guidance I can get to be a good citizen here.
Thank you.

**Comment by sigmavirus24** [comment]
Congrats @vpzee! To be as explicit as possible: if you're fixing a bug in a project, just fix the bug. Don't fix anything else in that pull request unless the project owner or maintainer ask you to. It makes reviewing the changes/fixes much easier for us and will improve your pull request's chances of being merged.

**Pull request merged**
