### PR TITLE
Add Python to PATH automatically

### PR DESCRIPTION
**Pull request by mahanmarwat**
Python latest installers for window have the option to automatically add Python to PATH.
I checked Python 2.7.10 and it has the option.
Please check this link http://www.howtogeek.com/197947/how-to-install-python-on-windows/ in case you wanted to
tweak the section.

### CODE REVIEW

**Comment by kennethreitz** [comment]
I think we should preserve this information, actually. It's pretty useful and this is a great place for it to live. Can you add the removed content so a subsection?

**Comment by mahanmarwat** [comment]
OK, I will send another PR.

**Comment by kennethreitz** [comment]
you can just push to your master and ping me here, it'll automatically get picked up!

**Comment by kennethreitz** [comment]
ping!

**Comment by ProfNandaa** [comment]
@kennethreitz - what was remaining here, I can pick it up and do the PR. cc. @mahanmarwat

**Comment by kennethreitz** [comment]
i think this is good information to have here... might need some refactoring, but it should exist in this guide

**Pull request closed without merging**
