### PR TITLE
added machine learning docs

### PR DESCRIPTION
**Pull request by shivenmian**
@kennethreitz @PaulReiber Started on a doc for Machine Learning, added some basic stuff about scikit-learn et al. Solves #755. 

Please review, would be happy to make edits if needed :)

### CODE REVIEW

**Comment by kennethreitz** [comment]
✨🍰✨

**Comment by shivenmian** [comment]
@kennethreitz nice! :D

**Comment by shivenmian** [comment]
@kennethreitz looks like this change hasn't shown up in the main docs.python-guide.org site. Is there something more I should do?

**Comment by kennethreitz** [comment]
@shivenmian oh, you need to add it to the table of contents!

**Comment by kennethreitz** [comment]
doing that now

**Comment by kennethreitz** [comment]
Python-Guide now has a Machine Learning section! http://docs.python-guide.org/en/latest/scenarios/ml/

**Comment by shivenmian** [comment]
@kennethreitz thank you! :D

but there's another thing though: when you go to http://docs.python-guide.org/en/latest/, in the contents on that page the Machine Learning article link (i.e the above link) isn't there: could you please check that too? :)

**Comment by kennethreitz** [comment]
it may be cached for you — it is there for me.

**Comment by shivenmian** [comment]
@kennethreitz cleared my cache, saw it. thanks! 🍰

**Pull request merged**
