### PR TITLE
fixed Gratipay button iframe width

### PR DESCRIPTION
**Pull request by romanpitak**
Fixed the iframe width to fit the whole gratipay button (and added a new line at the end of file). 

##### Before

before

##### After

after

### CODE REVIEW

**Comment by sigmavirus24** [comment]
screen shot 2015-10-02 at 12 25 17

This seems to be okay already. What browser/addons are you using?

**Comment by romanpitak** [comment]
Mozilla Firefox 41.0 (linux Mint)

Looks ok in Chrome, but doesn't fit in FF.

**Comment by sigmavirus24** [comment]
Do you have any javascript, adblocking, or other funky plugins installed?

**Comment by romanpitak** [comment]
I've disabled all plugins and extensions and it's still there. There wasn't much installed anyway - Greasemonkey, Kindle, Firebug, Tevtools toolbar, but I've turned them all off.

**Comment by sigmavirus24** [comment]
I'm keeping this open in the hopes someone else can reproduce this and show that this fixes it for them.

What resolution are you using by the way?

**Comment by lucyb1** [comment]
Hello, I have the same problem. (Linux, Fireox 41.0.1)

**Comment by romanpitak** [comment]
@sigmavirus24  1920x1080 if that's what you're asking

**Pull request closed without merging**
