### PR TITLE
virtualenv duplicate fix

### PR DESCRIPTION
**Pull request by varunagrawal**
Edited env.rst to remove duplication of virtualenv section and provide better flow to the actual virtualenv section.
Fix for #123

### CODE REVIEW

**Comment by sigmavirus24** [comment]
I'm not sure this is what that bug was suggesting happen. I think we wanted links to the virtualenv section with a very short mention of it here. There's still duplication.

**Comment by varunagrawal** [comment]
I did put a short description with just enough content to give a high level overview and generate interest for anyone looking into virtualenv. Any recommendations for what should be changed?

**Comment by varunagrawal** [comment]
Any updates on this?

**Comment by sigmavirus24** [comment]
On a second review this looks good. Thanks @varunagrawal

**Pull request merged**
