### PR TITLE
Add Python Community link

### PR DESCRIPTION
**Pull request by lukecaputo**
Add link for Python Community where being referenced.

### CODE REVIEW

**Comment by sigmavirus24** [comment]
You're removing a specific link to http://docs.python-guide.org/en/latest/intro/community/ which is where this link you wish to add actually belongs. 

Please fix this.

**Comment by lukecaputo** [comment]
The link, currently " :ref:`community <the-community>` " doesn't open anything. Figured it would be worth updating this link to something that actually went somewhere.

**Comment by sigmavirus24** [comment]
It does. Look at the correct section [here](http://docs.python-guide.org/en/latest/intro/duction/) and you'll see that it appropriately links to what I provided you.

The "link" you created won't go anywhere because you're using Markdown in reStructuredText. The latter doesn't understand the syntax of the former and it won't be rendered correctly.

Please update this appropriately.

**Comment by lukecaputo** [comment]
I understand what's going on now.... Sorry about that. I was check the links against what's listed on GitHub, not the published docs page. Thanks.

**Comment by sigmavirus24** [comment]
@lukecaputo do you plan on updating this PR?

**Pull request closed without merging**
