### PR TITLE
Updated with Chef , Buildout , Blueprint

### PR DESCRIPTION
**Pull request by IamRafy**

### CODE REVIEW

**Comment by sigmavirus24** [comment]
This conflicts, in part, with #586 which I intend to accept once it is cleaned up.

Please submit separate PRs for the following:

- Buildout
- Blueprint
- 99087bc
- e21f865

So they can be evaluated on *individual* merit.

**Comment by IamRafy** [comment]
Are those not merged ?
What is the problem ?

On Mon, Oct 19, 2015 at 12:04 AM, Ian Cordasco <notifications@github.com>
wrote:

> Closed #601 <https://github.com/kennethreitz/python-guide/pull/601>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kennethreitz/python-guide/pull/601#event-438529870>.
>



-- 
Best Regards ,
Mohammed Rafy
LinkedIn <https://in.linkedin.com/pub/mohammed-rafy/a2/b92/951> | Twitter
<https://twitter.com/RafyAsarmatta>  | Facebook
<https://www.facebook.com/asarmatta>
* ideabloom.wordpress.com *
+91-7204945348

**Comment by IamRafy** [comment]
I have to send 3 separate PR's for 3 different commit ?

On Mon, Oct 19, 2015 at 9:20 AM, De Scientist <mr.asarmatta@gmail.com>
wrote:

> Are those not merged ?
> What is the problem ?
>
> On Mon, Oct 19, 2015 at 12:04 AM, Ian Cordasco <notifications@github.com>
> wrote:
>
>> Closed #601 <https://github.com/kennethreitz/python-guide/pull/601>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/kennethreitz/python-guide/pull/601#event-438529870>.
>>
>
>
>
> --
> Best Regards ,
> Mohammed Rafy
> LinkedIn <https://in.linkedin.com/pub/mohammed-rafy/a2/b92/951> | Twitter
> <https://twitter.com/RafyAsarmatta>  | Facebook
> <https://www.facebook.com/asarmatta>
> * ideabloom.wordpress.com *
> +91-7204945348
>



-- 
Best Regards ,
Mohammed Rafy
LinkedIn <https://in.linkedin.com/pub/mohammed-rafy/a2/b92/951> | Twitter
<https://twitter.com/RafyAsarmatta>  | Facebook
<https://www.facebook.com/asarmatta>
* ideabloom.wordpress.com *
+91-7204945348

**Comment by IamRafy** [comment]
Would you mind telling whether it's cool ?

On Mon, Oct 19, 2015 at 12:04 AM, Ian Cordasco <notifications@github.com>
wrote:

> This conflicts, in part, with #586
> <https://github.com/kennethreitz/python-guide/pull/586> which I intend to
> accept once it is cleaned up.
>
> Please submit separate PRs for the following:
>
>    - Buildout
>    - Blueprint
>    - 99087bc
>    <https://github.com/kennethreitz/python-guide/commit/99087bc9da33c405c36338e4ff95cba8019147fb>
>    - e21f865
>    <https://github.com/kennethreitz/python-guide/commit/e21f865a492d8bb659c79b28a9f25c7a15e47167>
>
> So they can be evaluated on *individual* merit.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kennethreitz/python-guide/pull/601#issuecomment-149037226>
> .
>



-- 
Best Regards ,
Mohammed Rafy
LinkedIn <https://in.linkedin.com/pub/mohammed-rafy/a2/b92/951> | Twitter
<https://twitter.com/RafyAsarmatta>  | Facebook
<https://www.facebook.com/asarmatta>
* ideabloom.wordpress.com *
+91-7204945348

**Pull request closed without merging**
