### PR TITLE
IPython install edit

### PR DESCRIPTION
**Pull request by rajathkumarmp**
Installs IPython and also dependencies for IPython notebook.

### CODE REVIEW

**Comment by sigmavirus24** [comment]
Why not call that out separately?

**Comment by rajathkumarmp** [comment]
@sigmavirus24  This is fine?

**Comment by sigmavirus24** [comment]
"main optional" is a bit oxymoronic. Can we just trim out "main" here please?

**Comment by rajathkumarmp** [comment]
@sigmavirus24 Done.

**Pull request merged**
