### PR TITLE
PIL Link Fix

### PR DESCRIPTION
**Pull request by varunagrawal**
1. Added Dive Into Python for those looking to learn Python 2 first.
2. Fix for #569

### CODE REVIEW

**Comment by sigmavirus24** [comment]
Pull requests should be single purposed. Please only fix the PIL link for this. That is desirable.

If my memory serves me well, Dive Into Python covers Python 2.4 (or maybe 2.5) which is very out of date. I don't think we should be suggesting it at all in the Guide for that reason.

**Comment by varunagrawal** [comment]
Updated to only a single commit.
Also, I just went through the book, and Mr. Pilgrim recommends installing the latest version Python everywhere. There doesn't seem to be a dependency on a particular version of Python 2.x.

**Comment by sigmavirus24** [comment]
Even so, it's not appropriate to jam everything into one pull request.

**Comment by varunagrawal** [comment]
Yes I agree, I am sorry about that. Still not completely comfortable with how Pull Requests work. :(

**Pull request merged**
