### PR TITLE
Fixes #686

### LINKED ISSUE #686: Error on the Context Managers section ?
So what's said [here](http://docs.python-guide.org/en/latest/writing/structure/#context-managers) is :

```python
from contextlib import contextmanager

@contextmanager
def custom_open(filename):
    f = open(filename)
    yield f
    f.close()

with custom_open('file') as f:
    contents = f.read()
```

But as far as I undestand, we shoud wrap the ``yield`` into a ``try:`` block with the ``close`` in the ``finally:``, otherwise a exception might allow leaving the ``with`` block without calling ``close``. I might do a PR for this, but I wanted to check with someone if there was a reason the code was shown this way and/or if I was mistaken altogether...

### PR DESCRIPTION
**Pull request by ewjoachim**

### CODE REVIEW

**Comment by kennethreitz** [comment]
@sigmavirus24 thoughts?

**Comment by sigmavirus24** [comment]
Looks fine to me.

**Comment by kennethreitz** [comment]
:sparkles: :cake: :sparkles:

**Comment by ewjoachim** [comment]
:D Thank you !

**Comment by kennethreitz** [comment]
No, thank you! :)

**Pull request merged**
