### PR TITLE
more simple rm pyc files command

### PR DESCRIPTION
**Pull request by gruzovator**

### CODE REVIEW

**Comment by kennethreitz** [comment]
I haven't seen this one used nearly as often. It's been a number of years since I investigated why, but perhaps it was because of cross-platform compatibility?

**Comment by gruzovator** [comment]
I can't  find any sign of compatibility problems with -delete action of 'find'. GNU Findutils doc recommends '-delete' to delete files:
https://www.gnu.org/software/findutils/manual/html_node/find_html/Deleting-Files.html

**Comment by sigmavirus24** [comment]
> I haven't seen this one used nearly as often.

I have, but perhaps I use find more often?

> It's been a number of years since I investigated why, but perhaps it was because of cross-platform compatibility?

My guess would simply be that `-delete` is slightly newer and the older was just handed down to you.

**Comment by tylerdave** [comment]
`-delete` was added by BSD and has been in GNU find for quite a while now. There are still systems out there w/ older version of find that don't have the `-delete` action but I honestly doubt very many of them are being used for development at this point.

**Comment by kennethreitz** [comment]
Perfect, that's the answer I was looking for. I know at one point in my development career, '-delete' didn't work on OS X. 

Thanks!

**Comment by sigmavirus24** [comment]
>  I know at one point in my development career, '-delete' didn't work on OS X. 

Good thing no one actually uses OS X ;)

**Pull request merged**
