### PR TITLE
Update freezing.rst

### PR DESCRIPTION
**Pull request by codeNameMahi**
added basic example of py2app to make an .exe

### CODE REVIEW

**Comment by sigmavirus24** [comment]
Please include a link to the Tutorial that you summarized (https://pythonhosted.org/py2app/tutorial.html)

**Comment by sigmavirus24** [comment]
@codeNameMahi ping

**Comment by codeNameMahi** [comment]
added link to tutorial

**Comment by kennethreitz** [comment]
@codeNameMahi i'd love to include this! closing due to inactivity, but would love for you to re-submit it!

**Pull request closed without merging**
