### PR TITLE
added info for virtualenv-burrito

### PR DESCRIPTION
**Pull request by SanketDG**
with virtualenv-burrito, we can have a virtualenv + virtualenvwrapper
environment by typing out a single command.

https://github.com/brainsik/virtualenv-burrito

#325

### CODE REVIEW

**Comment by sigmavirus24** [comment]
virtualenv-burrito seems to be for people in a rush to install virtualenv/virtualenvwrapper which I expect people reading this document won't be.

Further, I don't think the guide should be advocating the ``curl ... | bash`` security anti-pattern.

**Comment by SanketDG** [comment]
> virtualenv-burrito seems to be for people in a rush to install virtualenv/virtualenvwrapper which I expect people reading this document won't be.

But it does act as a quick way of installing virtualenv+virtualenvwrapper on new machines for intermediate users.

> Further, I don't think the guide should be advocating the curl ... | bash security anti-pattern.

We could remove this, and just point to the repo instead.

**Comment by sigmavirus24** [comment]
> We could remove this, and just point to the repo instead.

That sounds better to me. If you can update this to remove that, I'll merge this.

**Comment by SanketDG** [comment]
@sigmavirus24 Done.

**Pull request merged**
