### PR TITLE
Update the link for latest available Python 2.7 release for Windows

### PR DESCRIPTION
**Pull request by codeaditya**

### CODE REVIEW

**Comment by kennethreitz** [comment]
many thanks!

**Comment by codeaditya** [comment]
Welcome and thanks for merging.

At the bottom of this file (along with files for linux and osx), in the section of [Virtual Environments](https://github.com/kennethreitz/python-guide/blob/master/docs/starting/install/win.rst#virtual-environments), the examples provided are for Django 1.3 and Django 1.0. These are for very old versions of Django. Do you mind if I update them to Django 1.10 (the latest) and Django 1.8 (the latest LTS) and send a pull request for it?

**Comment by kennethreitz** [comment]
that would be great! latest version numbers everywhere are welcome ;)

**Comment by codeaditya** [comment]
Thank you. Sending them soon :)

**Pull request merged**
