### PR TITLE
Python course for beginners

### PR DESCRIPTION
**Pull request by sjbarlas**
It really helped me as a beginner hence the recommendation. Also added an extra space (where necessary) in between each suggestion to make it more clear for other people who edit. Thanks!

### CODE REVIEW

**Comment by cornelinux** [comment]
Am 25.02.2015 um 21:51 schrieb Saira J. Barlas:
>
> It really helped me as a beginner hence the recommendation. Also added
> an extra space (where necessary) in between each suggestion to make it
> more clear for other people who edit. Thanks!
>
> ------------------------------------------------------------------------
>
>
>         You can view, comment on, or merge this pull request online at:
>
>   https://github.com/kennethreitz/python-guide/pull/520
>
>
>         Commit Summary
>
>   * Python course for beginners
>
>
>         File Changes
>
>   * *M* docs/intro/learning.rst
>     <https://github.com/kennethreitz/python-guide/pull/520/files#diff-0>
>     (11)
>
>
>         Patch Links:
>
>   * https://github.com/kennethreitz/python-guide/pull/520.patch
>   * https://github.com/kennethreitz/python-guide/pull/520.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kennethreitz/python-guide/pull/520>.
>

-- 
Cornelius Kölbel
Landgraf-Karl-Str. 19
34131 Kassel
0561 / 8167534

**Comment by sigmavirus24** [comment]
We generally prefer courses that are entirely free with the option to pay to support the author. Coursera is a partially free course with the *requirement* to pay to complete the course, if I remember correctly. In that case, I think we'd prefer not to include Coursera.

**Comment by sjbarlas** [comment]
Sorry but are you referring to codeacademy as coursera? Or did I misunderstand? Thanks though, please do as you see fit!

**Comment by sigmavirus24** [comment]
That's why I didn't close it. I was clearly confusing the two.

Thanks @sjbarlas! :cake:

**Pull request merged**
