### PR TITLE
Corrected typo.

### PR DESCRIPTION
**Pull request by lukecaputo**
Standardized spelling to match Oxford spelling throughout the rest of the text. Changed 'recognised' to 'recognized'.

### CODE REVIEW

**Comment by avinassh** [comment]
I don't think this is really required.

**Comment by sigmavirus24** [comment]
@avinassh care to provide reasoning for that thought?

**Comment by avinassh** [comment]
@sigmavirus24 both `recognised` and `recognized` are correct, former (`s` version) is preferred by British and latter (`z` version) is preferred by Americans. So I feel it's redundant to change to another, imho.

we don't another PR which changes back to `recognised` again lol. Just my thoughts.

**Comment by sigmavirus24** [comment]
@avinassh the difference is that this changing it to match the (apparent) de facto standard of Oxford (read American) spelling here.

**Comment by avinassh** [comment]
I just googled around and I read, looks like you guys are right.

I stand corrected.

**Pull request merged**
