### PR TITLE
Configuration management with chef

### PR DESCRIPTION
**Pull request by katmutua**
Include preliminary notes on using Chef for configuration management and add a practical reference for getting started with Ansible.

### CODE REVIEW

**Comment by sigmavirus24** [comment]
Hey @katmutua ! Thanks for the PR!

Since the PR is meant to flesh out the Chef section, would you mind sending a separate PR with 8583bf5 in it? The SHA in that PR doesn't have to match this one, but I'd rather that be separate.

Also, could you squash your last 4 commits? The have the same message and that makes the history a bit noisy. If you're not comfortable doing that, I can do it to when merging.

Ping me when you're ready for me to review this again or if you're new to git and having trouble squashing those commits.

Cheers,

**Comment by katmutua** [comment]
Sure no problem :+1:

**Comment by sigmavirus24** [comment]
@katmutua I squashed those commits for you and merged this branch manually. Thanks for the contribution! :cake:

**Comment by katmutua** [comment]
Awesome thanks!

**Pull request closed without merging**
