### PR TITLE
Include Bottle in web.rst

### PR DESCRIPTION
**Pull request by uvtc**
I think Bottle is different enough from Flask to be included here, in that it's distributed as a single file which can be dropped into your project and used straightaway. Very handy for whipping up little utility webapps without any dependencies.

### CODE REVIEW

**Comment by kennethreitz** [comment]
I don't believe that bottle has a place here — though I do like your argument.

Instead, perhaps we should just add a single sentence pointing readers to it as a possible (less popular) alternative, at the bottom of the Flask section.

**Comment by uvtc** [comment]
Ok. Removed that Bottle section I'd added, and instead added a sentence at the end of the Flask section.

**Comment by kennethreitz** [comment]
Thanks! I still may not merge this — will need to think about it some.

**Comment by uvtc** [comment]
Yup. You're welcome.

Another reason I like Bottle is that it *"just works"* with Python 3 (I drop the bottle.py file next to my-webapp.py and everything works). [The Flask install instructions](http://flask.pocoo.org/docs/0.11/installation/#installation) say to refer to [its Python 3 section](http://flask.pocoo.org/docs/0.11/python3/#python3-support), which explains a bit about mininum versions of Jinja and Werkzeug, and also unicode support.

**Pull request closed without merging**
